# Generated by Django 2.0 on 2017-12-15 19:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171215_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 19, 55, 23, 578700, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
