# Generated by Django 2.0 on 2017-12-15 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171215_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2017, 12, 15, 20, 2, 51, 300443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cat',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
